"#narrators" = "Simon Vance"
id = "49"
authors = "Frank Herbert"
description = "More than 3,000 years have passed since the first events recorded in <i>Dune</i>. Only one link survives with those tumultuous times: the grotesque figure of Leto Atreides, son of the prophet Paul Muad'Dib, and now the virtually immortal God Emperor of Dune. He alone understands the future, and he knows with a terrible certainty that the evolution of his race is at an end unless he can breed new qualities into his species. <p>But to achieve his final victory, Leto Atreides must also bring about his own downfall.</p>"
languages = "english"
position = "4"
published = "2007-12-30"
publisher = "Macmillan Audio"
series = "Dune"
title = "God Emperor of Dune"
